version: 1
update_configs:
- package_manager: "php:composer"
  directory: "/assignment"
  update_schedule: "daily"
- package_manager: "javascript"
  directory: "/assignment"
  update_schedule: "daily"
